name = "tools-directory"
compatibility_date = "2024-11-20"
pages_build_output_dir = "dist"

[assets]
binding = "CF_ASSETS"
directory = "dist/client"

[[ d1_databases ]]
binding = "DB"
database_name = "ai-tools"
database_id   = "5c59f883-511f-4a79-bf4a-5ce6e2e9b38b"

[[ kv_namespaces ]]
binding = "CACHE"
id      = "ae59198110e24994b4111d33bbab0f5e"

[vars]
GEMINI_API_KEY = "AIzaSyAtR4SzX6vYdC7Jlhr0435CgX17TsyWzIU"   # Set in Pages dashboard, not here
